#!/usr/bin/env bash
set -euo pipefail

# incident-digest.sh — weekly incident summary
#
# Usage:
#   ./scripts/incident-digest.sh [--discord]
#
# Outputs a Markdown report of the last 7 days of incidents.
# Pass --discord to also post the report to your configured webhook.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${OPENCLAW_LOG_DIR:-${OPENCLAW_CONFIG_DIR:-$HOME/.openclaw}/logs}"
DISCORD_FLAG="${1:-}"

# ─── Date helper (portable: macOS + Linux) ───────────────────────────────────
if date -d "7 days ago" +%Y-%m-%d &>/dev/null 2>&1; then
    # GNU date (Linux)
    SINCE=$(date -d "7 days ago" +%Y-%m-%d)
    PERIOD_END=$(date +%Y-%m-%d)
else
    # BSD date (macOS)
    SINCE=$(date -v-7d +%Y-%m-%d)
    PERIOD_END=$(date +%Y-%m-%d)
fi

# ─── Count incidents from logs ───────────────────────────────────────────────
TOTAL=0
AUTO=0
HUMAN=0

if [[ -d "$LOG_DIR" ]]; then
    # Total incidents: any crash/failure/recovery trigger event
    TOTAL=$(grep -r \
        -e "INCIDENT" \
        -e "failure detected" \
        -e "recovery triggered" \
        -e "crash detected" \
        -e "gateway.*down" \
        "$LOG_DIR" 2>/dev/null \
        | awk -v since="$SINCE" '{ if (substr($0,1,10) >= since) print }' \
        | wc -l \
        | tr -d ' ' || echo 0)

    # Auto-resolved: recovery succeeded without human
    AUTO=$(grep -r \
        -e "auto-resolved" \
        -e "recovery success" \
        -e "level.*resolved" \
        -e "gateway.*recovered" \
        -e "restart.*success" \
        "$LOG_DIR" 2>/dev/null \
        | awk -v since="$SINCE" '{ if (substr($0,1,10) >= since) print }' \
        | wc -l \
        | tr -d ' ' || echo 0)

    # Human-escalated: Level 4 alerts fired
    HUMAN=$(grep -r \
        -e "escalated to human" \
        -e "level 4" \
        -e "alert sent" \
        -e "discord.*alert" \
        -e "telegram.*alert" \
        "$LOG_DIR" 2>/dev/null \
        | awk -v since="$SINCE" '{ if (substr($0,1,10) >= since) print }' \
        | wc -l \
        | tr -d ' ' || echo 0)
fi

# Ensure values are integers
TOTAL=$(( TOTAL + 0 ))
AUTO=$(( AUTO + 0 ))
HUMAN=$(( HUMAN + 0 ))

# Clamp AUTO to TOTAL (log overlap can inflate it)
[[ $AUTO -gt $TOTAL ]] && AUTO=$TOTAL

# If no explicit human-escalation log lines, derive from remainder
if [[ $HUMAN -eq 0 && $TOTAL -gt 0 ]]; then
    HUMAN=$(( TOTAL - AUTO ))
fi

# ─── Autonomy rate ────────────────────────────────────────────────────────────
RATE=0
if [[ $TOTAL -gt 0 ]]; then
    RATE=$(( AUTO * 100 / TOTAL ))
fi

# ─── Status verdict ───────────────────────────────────────────────────────────
if [[ $TOTAL -eq 0 ]]; then
    VERDICT="✅ No incidents detected — system running cleanly"
elif [[ $RATE -ge 60 ]]; then
    VERDICT="✅ System performing well (autonomy rate on target)"
elif [[ $RATE -ge 30 ]]; then
    VERDICT="⚠️  Recovery rate below target — review logs"
else
    VERDICT="🚨 High escalation rate — manual review recommended"
fi

# ─── Build report ─────────────────────────────────────────────────────────────
REPORT="## 📊 Weekly Incident Digest

**Period**: ${SINCE} → ${PERIOD_END}
**Log directory**: \`${LOG_DIR}\`

| Metric | Value |
|--------|-------|
| Total incidents | ${TOTAL} |
| Auto-resolved | ${AUTO} (${RATE}%) |
| Escalated to human | ${HUMAN} |
| Autonomy rate | ${RATE}% |

${VERDICT}

---
*Generated by openclaw-self-healing \`incident-digest.sh\`*"

# ─── Output ───────────────────────────────────────────────────────────────────
echo "$REPORT"

# ─── Optional Discord post ────────────────────────────────────────────────────
if [[ "$DISCORD_FLAG" == "--discord" ]]; then
    NOTIFY_LIB="$SCRIPT_DIR/lib/notify.sh"
    if [[ -f "$NOTIFY_LIB" ]]; then
        # shellcheck source=scripts/lib/notify.sh
        source "$NOTIFY_LIB"
        send_notification "Weekly Incident Digest" "$REPORT" "info" 2>/dev/null || true
        echo "" >&2
        echo "📨 Report posted to Discord." >&2
    else
        echo "⚠️  notify.sh not found at $NOTIFY_LIB — skipping Discord post." >&2
    fi
fi
