#!/usr/bin/env python3
"""
Trading Strategy
================

Auto-generated by Crypto Backtest Skill
https://github.com/0xrikt/crypto-skills

Asset: BTC/USDT
Timeframe: 6h

Entry: rsi<35,price<sma200*0.95,price<bb_lower,drawdown<-25,volume_ratio>1.5
Exit: rsi>70,price>sma200*1.15,price>bb_upper
Stop Loss: 8.0%
Take Profit: 15%
"""

import ccxt
import pandas as pd
import pandas_ta as ta
from datetime import datetime, timedelta


# =============================================================================
# CONFIGURATION
# =============================================================================

SYMBOL = "BTC/USDT"
TIMEFRAME = "6h"
EXCHANGE = "binance"

# Risk Management
INITIAL_CAPITAL = 10000
POSITION_SIZE_PCT = 20.0  # % of portfolio per trade
STOP_LOSS_PCT = 8.0
TAKE_PROFIT_PCT = 15
COMMISSION_PCT = 0.1


# =============================================================================
# DATA FETCHING
# =============================================================================

def fetch_data(days: int = 365) -> pd.DataFrame:
    """Fetch historical OHLCV data."""
    exchange = getattr(ccxt, EXCHANGE)({'enableRateLimit': True})
    since = exchange.parse8601((datetime.utcnow() - timedelta(days=days)).isoformat())
    
    all_ohlcv = []
    while True:
        ohlcv = exchange.fetch_ohlcv(SYMBOL, TIMEFRAME, since=since, limit=1000)
        if not ohlcv:
            break
        all_ohlcv.extend(ohlcv)
        since = ohlcv[-1][0] + 1
        if len(ohlcv) < 1000:
            break
    
    df = pd.DataFrame(all_ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df.set_index('timestamp', inplace=True)
    return df


# =============================================================================
# INDICATORS
# =============================================================================

def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Calculate technical indicators."""
    df = df.copy()
    
    # RSI
    df['rsi'] = ta.rsi(df['close'], length=14)
    
    # MACD
    macd = ta.macd(df['close'], fast=12, slow=26, signal=9)
    if macd is not None:
        df['macd'] = macd.iloc[:, 0]
        df['macd_signal'] = macd.iloc[:, 2]
    
    # Moving Averages
    df['sma50'] = ta.sma(df['close'], length=50)
    df['ema21'] = ta.ema(df['close'], length=21)
    
    # Bollinger Bands
    bb = ta.bbands(df['close'], length=20, std=2.0)
    if bb is not None:
        df['bb_upper'] = bb.iloc[:, 2]
        df['bb_lower'] = bb.iloc[:, 0]
    
    return df


# =============================================================================
# SIGNAL GENERATION
# =============================================================================

def generate_signals(df: pd.DataFrame) -> pd.DataFrame:
    """Generate entry and exit signals."""
    df = df.copy()
    
    # Entry conditions: rsi<35,price<sma200*0.95,price<bb_lower,drawdown<-25,volume_ratio>1.5
    entry = pd.Series(True, index=df.index)
    # TODO: Customize entry conditions
    entry &= df['rsi'] < 30  # Example
    
    # Exit conditions: rsi>70,price>sma200*1.15,price>bb_upper
    exit_signal = pd.Series(False, index=df.index)
    # TODO: Customize exit conditions
    exit_signal |= df['rsi'] > 70  # Example
    
    df['entry_signal'] = entry.astype(int)
    df['exit_signal'] = exit_signal.astype(int)
    
    return df


# =============================================================================
# BACKTEST
# =============================================================================

def backtest(df: pd.DataFrame) -> dict:
    """Run backtest simulation."""
    capital = INITIAL_CAPITAL
    position = 0.0
    entry_price = 0.0
    trades = []
    
    for timestamp, row in df.iterrows():
        price = row['close']
        
        # Check stop-loss / take-profit
        if position > 0:
            pnl_pct = (price - entry_price) / entry_price * 100
            
            if pnl_pct <= -STOP_LOSS_PCT:
                proceeds = position * price * (1 - COMMISSION_PCT / 100)
                capital += proceeds
                trades.append({'pnl_pct': pnl_pct, 'reason': 'stop_loss'})
                position = 0
            
            elif pnl_pct >= TAKE_PROFIT_PCT:
                proceeds = position * price * (1 - COMMISSION_PCT / 100)
                capital += proceeds
                trades.append({'pnl_pct': pnl_pct, 'reason': 'take_profit'})
                position = 0
        
        # Entry
        if row['entry_signal'] == 1 and position == 0:
            position_value = capital * POSITION_SIZE_PCT / 100
            position = position_value / price
            entry_price = price
            capital -= position_value * (1 + COMMISSION_PCT / 100)
        
        # Exit
        elif row['exit_signal'] == 1 and position > 0:
            proceeds = position * price * (1 - COMMISSION_PCT / 100)
            pnl_pct = (price - entry_price) / entry_price * 100
            capital += proceeds
            trades.append({'pnl_pct': pnl_pct, 'reason': 'signal'})
            position = 0
    
    # Close remaining
    if position > 0:
        capital += position * df.iloc[-1]['close']
    
    return {
        'final_capital': capital,
        'return_pct': (capital - INITIAL_CAPITAL) / INITIAL_CAPITAL * 100,
        'total_trades': len(trades),
        'trades': trades
    }


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print(f"Fetching {SYMBOL} data...")
    df = fetch_data(days=365)
    print(f"Got {len(df)} candles")
    
    print("Calculating indicators...")
    df = calculate_indicators(df)
    
    print("Generating signals...")
    df = generate_signals(df)
    
    print("Running backtest...")
    results = backtest(df)
    
    print("\n" + "="*50)
    print("BACKTEST RESULTS")
    print("="*50)
    print(f"Final Capital: ${results['final_capital']:,.2f}")
    print(f"Return: {results['return_pct']:+.2f}%")
    print(f"Total Trades: {results['total_trades']}")
