#!/bin/bash
set -e

# PR Diff Script
# Fetches and formats PR diff for code review

PR_NUMBER="${1:-}"
REPO="${2:-}"
OUTPUT_FORMAT="${3:-markdown}"

cleanup() {
    if [ -n "$TEMP_DIR" ] && [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"
    fi
}
trap cleanup EXIT

show_usage() {
    cat << 'EOF'
Usage: pr-diff.sh <pr-number> [repo] [format]

Arguments:
  pr-number     Pull request number (required)
  repo          Repository in owner/repo format (default: from git remote)
  format        Output format: markdown, json, plain (default: markdown)

Examples:
  pr-diff.sh 123
  pr-diff.sh 123 owner/repo
  pr-diff.sh 123 owner/repo json

Output:
  - PR metadata (title, author, base branch)
  - Changed files list
  - Diff content formatted for review

Requirements:
  - gh CLI installed and authenticated
EOF
}

# Check if gh is installed
if ! command -v gh &> /dev/null; then
    echo '{"success": false, "error": "gh CLI is not installed"}'
    exit 1
fi

# Validate PR number
if [ -z "$PR_NUMBER" ]; then
    show_usage >&2
    echo '{"success": false, "error": "PR number is required"}'
    exit 1
fi

# Get repo from git remote if not provided
if [ -z "$REPO" ]; then
    REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || echo "")
    if [ -z "$REPO" ]; then
        echo '{"success": false, "error": "Could not determine repository. Please provide repo argument."}'
        exit 1
    fi
fi

echo "Fetching PR #$PR_NUMBER from $REPO..." >&2

TEMP_DIR=$(mktemp -d)

# Fetch PR metadata
echo "Fetching PR metadata..." >&2
PR_DATA=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json title,author,baseRefName,headRefName,additions,deletions,changedFiles,state,mergeable,createdAt,body 2>&1)
if [ $? -ne 0 ]; then
    echo '{"success": false, "error": "Failed to fetch PR: '"$PR_DATA"'"}'
    exit 1
fi

# Extract fields
TITLE=$(echo "$PR_DATA" | jq -r '.title')
AUTHOR=$(echo "$PR_DATA" | jq -r '.author.login')
BASE_BRANCH=$(echo "$PR_DATA" | jq -r '.baseRefName')
HEAD_BRANCH=$(echo "$PR_DATA" | jq -r '.headRefName')
ADDITIONS=$(echo "$PR_DATA" | jq -r '.additions')
DELETIONS=$(echo "$PR_DATA" | jq -r '.deletions')
CHANGED_FILES=$(echo "$PR_DATA" | jq -r '.changedFiles')
STATE=$(echo "$PR_DATA" | jq -r '.state')

# Fetch changed files list
echo "Fetching changed files..." >&2
FILES=$(gh pr diff "$PR_NUMBER" --repo "$REPO" --name-only 2>&1)

# Fetch diff
echo "Fetching diff..." >&2
DIFF=$(gh pr diff "$PR_NUMBER" --repo "$REPO" 2>&1)

case "$OUTPUT_FORMAT" in
    json)
        # Escape diff for JSON
        DIFF_ESCAPED=$(echo "$DIFF" | jq -Rs .)
        FILES_ARRAY=$(echo "$FILES" | jq -R . | jq -s .)

        cat << EOF
{
  "success": true,
  "pr": {
    "number": $PR_NUMBER,
    "title": "$TITLE",
    "author": "$AUTHOR",
    "base": "$BASE_BRANCH",
    "head": "$HEAD_BRANCH",
    "state": "$STATE",
    "additions": $ADDITIONS,
    "deletions": $DELETIONS,
    "changed_files": $CHANGED_FILES
  },
  "files": $FILES_ARRAY,
  "diff": $DIFF_ESCAPED
}
EOF
        ;;

    markdown)
        cat << EOF
# PR #$PR_NUMBER: $TITLE

## Metadata
| Field | Value |
|-------|-------|
| Author | @$AUTHOR |
| State | $STATE |
| Base | \`$BASE_BRANCH\` |
| Head | \`$HEAD_BRANCH\` |
| Changes | +$ADDITIONS / -$DELETIONS |
| Files | $CHANGED_FILES |

## Changed Files
\`\`\`
$FILES
\`\`\`

## Diff
\`\`\`diff
$DIFF
\`\`\`

---
*Generated by pr-diff.sh*
EOF
        ;;

    plain)
        cat << EOF
PR #$PR_NUMBER: $TITLE
Author: $AUTHOR
State: $STATE
Base: $BASE_BRANCH <- Head: $HEAD_BRANCH
Changes: +$ADDITIONS / -$DELETIONS ($CHANGED_FILES files)

Changed Files:
$FILES

Diff:
$DIFF
EOF
        ;;

    *)
        echo '{"success": false, "error": "Unknown format: '"$OUTPUT_FORMAT"'"}'
        exit 1
        ;;
esac
